stages:
  - deploy
  - cleanup

deploy:
  image: docker:latest
  stage: deploy
  only:
    - dev
    - main
  variables:
    DB_URL: $DATABASE_URL
    COOKIE_PW: $COOKIE_PASSWORD
    M_ID: $MAIL_ID
    M_PW: $MAIL_PASSWORD
    NAVER_ID: $NEXT_PUBLIC_NAVER_CLIENT_ID
    NAVER_SECRET: $NEXT_PUBLIC_NAVER_CLIENT_SECRET
    KAKAO_KEY: $NEXT_PUBLIC_KAKAO_KEY
    AI_KEY: $AI_API_KEY
    FLASK_API: http://flask:8080
    AC_ID: $ACCESSKEYID
    SC_KET: $SECRETACCESSKET
    REG: $REGION
  before_script:
    - echo -e "DATABASE_URL="$DB_URL >> .env
    - echo -e "\nCOOKIE_PASSWORD="$COOKIE_PW >> .env
    - echo -e "\nMAIL_ID="$M_ID >> .env
    - echo -e "\nMAIL_PASSWORD="$M_PW >> .env
    - echo -e "\nNEXT_PUBLIC_NAVER_CLIENT_ID="$NAVER_ID >> .env
    - echo -e "\nNEXT_PUBLIC_NAVER_CLIENT_SECRET="$NAVER_SECRET >> .env
    - echo -e "\nNEXT_PUBLIC_KAKAO_KEY="$KAKAO_KEY >> .env
    - echo -e "\nAI_API_KEY="$AI_KEY >> .env
    - echo -e "\nFLASK_API="$FLASK_API >> .env
    - echo -e "\nACCESSKEYID="$AC_ID >> .env
    - echo -e "\nSECRETACCESSKET="$SC_KET >> .env
    - echo -e "\nREGION="$REG >> .env
    - cp .env /builds/ai_track/class05/ai_project/team01/team01/next
  script:
    - docker-compose up -d --build

cleanup:
  image: ubuntu:latest
  stage: cleanup
  only:
    - dev
    - main
  script:
    - docker rmi $(docker images -f "dangling=true" -q)
