stages:
  - deploy

deploy:
  image: docker:latest
  stage: deploy
  only:
    - dev
    - feat/connect-api
  script:
    - cp $ENV_FILE .env
    - docker-compose config
    - docker-compose build
    - docker-compose up -d
    - docker ps
