stages:
  - deploy

deploy:
  image: docker:latest
  stage: deploy
  only:
    - dev
    - feat/connect-api
  variables:
    DATABASE_URL: $DATABASE_URL
    COOKIE_PASSWORD: $COOKIE_PASSWORD
    MAIL_ID: $MAIL_ID
    MAIL_PASSWORD: $MAIL_PASSWORD
    NEXT_PUBLIC_NAVER_CLIENT_ID: $NEXT_PUBLIC_NAVER_CLIENT_ID
    NEXT_PUBLIC_NAVER_CLIENT_SECRET: $NEXT_PUBLIC_NAVER_CLIENT_SECRET
    NEXT_PUBLIC_KAKAO_KEY: $NEXT_PUBLIC_KAKAO_KEY
    AI_API_KEY: $AI_API_KEY
    GITHUB_ID: $GITHUB_ID
    GITHUB_SECRET: $GITHUB_SECRET
    NEXTAUTH_URL: $NEXTAUTH_URL
  script:
    - docker-compose up -d
